# Generated by Django 4.2.7 on 2024-01-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcenter',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
