# Generated by Django 4.2.7 on 2024-06-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_learningcenter_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcenter',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
