# Generated by Django 5.2.1 on 2026-03-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0003_alter_learningcenter_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningcenter',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='category',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='courses_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='headline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='mentors_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='seo_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='students_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningcenter',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='categories',
            field=models.ManyToManyField(related_name='centers', to='centers.category'),
        ),
        migrations.AlterField(
            model_name='learningcenter',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
