# Generated by Django 4.2.7 on 2024-01-10 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_videocontent_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='cover_image',
            field=models.ImageField(default=datetime.datetime(2024, 1, 10, 7, 0, 34, 442642, tzinfo=datetime.timezone.utc), upload_to='video_images/'),
            preserve_default=False,
        ),
    ]
