# Generated by Django 4.2.7 on 2024-06-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
    ]
