# Generated by Django 4.2.7 on 2026-09-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_options_alter_videocontent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
