# Generated by Django 4.2.16 on 2026-04-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_options_alter_videocontent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
