# Generated by Django 5.2.1 on 2026-03-30 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_initial'),
        ('courses', '0006_alter_course_options_alter_videocontent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=160)),
                ('quote', models.TextField()),
                ('avatar_url', models.URLField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('translations', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together={('user', 'course')},
        ),
    ]
