# Generated by Django 4.2.7 on 2026-09-18 06:47

import django.core.validators
from django.db import migrations, models


def normalize_ratings_and_metrics(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    UserCourse = apps.get_model('connections', 'UserCourse')
    UserCourseRating = apps.get_model('connections', 'UserCourseRating')

    # Preserve the newest rating if old data contains more than one per user/course.
    seen = set()
    for rating in UserCourseRating.objects.order_by('-created_at', '-pk'):
        key = (rating.user_id, rating.course_id)
        if key in seen:
            rating.delete()
        else:
            seen.add(key)

    for course in Course.objects.all():
        ratings = list(UserCourseRating.objects.filter(course_id=course.pk).values_list('rating', flat=True))
        course.students_count = UserCourse.objects.filter(course_id=course.pk).count()
        course.rating = round(sum(ratings) / len(ratings), 1) if ratings else 0
        course.save(update_fields=['students_count', 'rating'])


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_testimonial_alter_usercourse_unique_together'),
        ('courses', '0007_enforce_course_metrics'),
    ]

    operations = [
        migrations.RunPython(normalize_ratings_and_metrics, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='usercourserating',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='usercourserating',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique_user_course_rating'),
        ),
    ]
