# Generated by Django 4.2.16 on 2026-04-11 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connections', '0003_testimonial_alter_usercourse_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourserating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterUniqueTogether(
            name='usercourserating',
            unique_together={('user', 'course')},
        ),
    ]
