# Generated by Django 5.2.1 on 2026-03-30 18:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.utils.text import slugify


def populate_blog_slugs(apps, schema_editor):
    BlogPost = apps.get_model('blogs', 'BlogPost')
    used = set()
    for blog in BlogPost.objects.all().order_by('id'):
        base_slug = slugify(blog.title) or f'blog-{blog.id}'
        slug = base_slug
        counter = 2
        while slug in used or BlogPost.objects.exclude(pk=blog.pk).filter(slug=slug).exists():
            slug = f'{base_slug}-{counter}'
            counter += 1
        blog.slug = slug
        blog.save(update_fields=['slug'])
        used.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_name',
            field=models.CharField(default='Asilbek Mirolimov', max_length=128),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='published_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reading_time',
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='topic',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='blog_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blogs.blogpost'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=180),
        ),
        migrations.RunPython(populate_blog_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
