# Generated by Django 4.2.7 on 2024-01-11 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+998\\d{9,15}$', message='Phone number must be in the format +998XXXXXXXXX, where X is a digit.')]),
        ),
    ]
