# Generated by Django 5.2.1 on 2026-03-30 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('bio', models.TextField()),
                ('mission', models.TextField()),
                ('profile_description', models.TextField(blank=True)),
                ('experience_years', models.PositiveSmallIntegerField(default=5)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('website', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
