# Generated by Django 4.2.7 on 2023-11-26 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningcenter',
            name='slug',
        ),
    ]
